.TH QUICKHASH 1 "" "January 2018"
.SH NAME
quickhash - graphical file hashing tool
.SH SYNOPSIS
.B quickhash
.SH OPTIONS
This program has no command line options.
.SH DESCRIPTION
Quickhash is a graphical means for users to easily hash data such as text, files, or even disks using Linux without knowing command line syntax. 

It can also be used for copying files from one folder to another where hashes are computed prior to copying and afterwards.

Users can compare to files, or compare two folders, using hash anaysis to be sure one matches the othe
.SH SEE ALSO
.I http://quickhash\-gui.org/
.SH AUTHOR
Copyright 2011\-2018, Ted Smith <tedsmith28@yahoo.co.uk>
